### ISSUE TITLE
Can't find variable: bonfirm

### ISSUE THREAD

**Issue by Gob-Lin** [brijeshb42/blurt#1]
Looks like the bonfirm() method isn't available. Can you confirm?

Thanks,

P

**Comment by brijeshb42** [comment]
Actually I did not create that. There are only two functions available as displayed on the [demo page](http://bitwiser.in/blurt/).
I was going to create that but got caught up.
You should use [my other project](http://bitwiser.in/medium-style-confirm/). It has all the three functionalities and the interface is lot simple.

**Comment by Gob-Lin** [comment]
Good to know, thank you. You should however consider removing the bonfirm() reference from the page, it can be misleading.

**Comment by brijeshb42** [comment]
Just did that. Thanks.
