### ISSUE TITLE
"okButtonText" does not appear to be working in FireFox

### ISSUE THREAD

**Issue by jonlarsen86** [brijeshb42/blurt#2]
when I customize my blurt with something such as the following:

blurt({
                    title: "Error",
                    text: error.GetSummaryDetailDataResult.Message,
                    type: "error",
                    okButtonText: "Close",
                    escapable: true
                });

The okButtonText appears in both Chrome and IE but does not show up for any of my buttons in FireFox.  I'm using the latest version of all three browsers.

see below for a couple of sample screenshots:

![error](https://cloud.githubusercontent.com/assets/11844473/11510535/690a48e4-9821-11e5-8459-af89e9460eac.PNG)
![success](https://cloud.githubusercontent.com/assets/11844473/11510582/9f7bc498-9821-11e5-872c-03d234bf0ef5.PNG)

**Comment by brijeshb42** [comment]
@jonlarsen86 I would recommend you use [http://bitwiser.in/medium-style-confirm/](http://bitwiser.in/medium-style-confirm/). Its api is the same as of blurt while I try to fix this.

**Comment by jonlarsen86** [comment]
Thanks, I'll take a look.
