### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by nickeyzh** [brijeshb42/blurt#4]
The brompt does not show focus on input on phones, but only on web, possible to fix ?

**Comment by nickeyzh** [comment]
Would be great also with popup, without any ok/cancel

**Comment by oeresundsgruppen** [comment]
Possible to add <br> or \r\n line returns to text in popup's ?

**Comment by brijeshb42** [comment]
There is no new development on this project. I would recommend you use [medium-style-confirm](https://github.com/brijeshb42/medium-style-confirm) instead. It has all the APIs of blurt.

cc @nickeyzh @oeresundsgruppen fixes for both of your issues are already there in it.

**Comment by oeresundsgruppen** [comment]
medium-style-confirm looks rather 1920's, grey-style.
